# Usa uma imagem base do Node.js. Alpine é uma versão leve.
FROM node:22-alpine

# Define o diretório de trabalho dentro do container.
WORKDIR /usr/src/app

# Copia o package.json (e package-lock.json, se existir) para o diretório de trabalho.
# O '*' garante que ambos os arquivos sejam copiados se existirem.
COPY package*.json ./

# Instala as dependências do projeto.
RUN npm install --no-audit --no-fund --legacy-peer-deps

# Copia o restante dos arquivos da API para o diretório de trabalho.
COPY . .

# Expõe a porta em que a API vai rodar.
EXPOSE 3000

# Comando para iniciar a aplicação quando o container for executado.
CMD [ "node", "index.js" ]
